name: deploy-storybook

on:
  push:	
    branches:	
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      id: npm-modules
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - run: npm install
      if: steps.npm-modules.outputs.cache-hit != 'true'
    - run: npm run deploy-storybook -- --ci 
      env:
        GH_TOKEN: delianides:${{ secrets.GITHUB_TOKEN }}
    
